### ISSUE TITLE
Feedback Task Pertemuan 3

### ISSUE THREAD

**Issue by aufaroot18** [ahmad-milzam/frontend-programming#1]
## Perbaikan

- Pada method `find` dan `filter` tidak perlu membuat object `user` lagi. Tinggal cari saja datanya.

## Improvement (Hal yang bisa ditingkatkan)

- Pada fungsi `map` di `formatUser`, dapat menggunakan spread operator untuk mengupdate object. Ex: ``{ ...user, name: `${title}. ${user.name}` }``
- Return pada arrow function bisa dipersingkat menjadi sebaris

**Comment by ahmad-milzam** [comment]
Terimakasih kak, untuk saran perbaikan dan improvement nya 🙏

**Comment by aufaroot18** [comment]
Baik sama-sama.
